packages:
  - .

enableGlobalVirtualStore: true

enablePrePostScripts: false

ignorePatchFailures: false

packageExtensions:
  "@typia/core@*":
    peerDependencies:
      typescript: "*"
  "@typia/transform@*":
    peerDependencies:
      typescript: "*"

ignoredBuiltDependencies:
  - core-js
  - esbuild

onlyBuiltDependencies:
  - dprint

optimisticRepeatInstall: true

resolutionMode: lowest-direct

verifyDepsBeforeRun: install
