packages:
  - .

enableGlobalVirtualStore: true

enablePrePostScripts: false

ignorePatchFailures: false

packageExtensions:
  "@typia/core@*":
    peerDependencies:
      typescript: "*"
  "@typia/transform@*":
    peerDependencies:
      typescript: "*"

allowBuilds:
  core-js: false
  dprint: true
  esbuild: false

optimisticRepeatInstall: true

resolutionMode: lowest-direct

verifyDepsBeforeRun: install
